CREATE OR ALTER FUNCTION ISINTEGER
(
	@value sql_variant  
)
RETURNS BIT
AS
BEGIN	
	DECLARE @retVAL BIT = 0;
	IF (TRY_CAST(TRY_CAST(@value AS NVARCHAR(MAX)) AS INTEGER) IS NOT NULL)
		SET @retVAL = 1;

		RETURN @retVAL;
END;
GO